FROM golang:1.16-alpine
WORKDIR /
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY *.go .
RUN go build -o /goBackend
ENV MONGO_USER userp1
ENV MONGO_PASS userp1password
ENV MONGO_HOST 192.168.1.12
ENV MONGO_PORT 27017
ENV FRONT_PORT 3000
ENV API_PORT 5000
EXPOSE 5000
CMD ["/goBackend"]