apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never

  containers:
    - name: uno
      image: stevengez/goclient_grpc

    - name: dos
      image: stevengez/nodeserver_grpc

    

