apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
spec:
  replicas: 1
  resources:
    requests:
      cpu: 800m
      memory: 1Gi
    limits: 
      cpu: 1000m
      memory: 2Gi
