## Local build case
# services:
#   backend:
#     build: "./BackEnd"
#     container_name: mybackend
#     environment:
#       - MONGO_USER=root
#       - MONGO_PASS=Keyuser95
#       - MONGO_HOST=192.168.1.12
#     ports:
#       - "5000:5000"
#   frontend:
#     build: "./FrontEnd"
#     container_name: myfront
#     environment:
#       - REACT_APP_API_HOST=http://192.168.1.12
#       - REACT_APP_API_PORT=5000
#     ports:
#       - "3000:3000"

## Local Images Case
# services:
#   db: 
#     image: mongo
#     container_name: mongodb
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=Keyuser95
#     ports:
#       - "27017:27017"
#   backend:
#     image: sp1_backend
#     container_name: mybackend
#     environment:
#       - MONGO_USER=root
#       - MONGO_PASS=Keyuser95
#       - MONGO_HOST=192.168.1.12
#       - MONGO_PORT=27017
#     ports:
#       - "5000:5000"
#   frontend:
#     image: sp1_frontend
#     container_name: myfront
#     environment:
#       - REACT_APP_API_HOST=http://192.168.1.12
#       - REACT_APP_API_PORT=5000
#     ports:
#       - "3000:3000"

## Cloud Deployment Case
services:
  db: 
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userp1
      - MONGO_INITDB_ROOT_PASSWORD=userp1password
    ports:
      - "27017:27017"
    volumes:
      - mongoVolume:/data/db:rw
  # backend:
  #   image: stevengez/backend_p1_201602938:latest
  #   container_name: mybackend
  #   environment:
  #     - MONGO_USER=userp1
  #     - MONGO_PASS=userp1password
  #     - MONGO_HOST=192.168.1.12
  #     - MONGO_PORT=27017
  #   ports:
  #     - "5000:5000"
  frontend:
    image: stevengez/frontend_p1_201602938:latest
    container_name: myfront
    environment:
      - REACT_APP_API_HOST=http://192.168.1.12
      - REACT_APP_API_PORT=5000 
    ports:
      - "3000:3000"
volumes:
  mongoVolume:

      
      