FROM golang:1.16-alpine
WORKDIR /
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN mkdir Proto
COPY Proto/* ./Proto/
COPY *.go . 
RUN go build -o gRPC-Client
ENV gRPC_SERVER_IP 127.0.0.1
ENV gRPC_SERVER_PORT 50051
ENV API_GO_PORT 5000
EXPOSE 5000
CMD ["/gRPC-Client"]
